version: '3.8'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      - RABBITMQ_USERNAME=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
    ports:
      - '15672:15672'
    volumes:
      - 'data:/bitnami/rabbitmq/mnesia'
volumes:
  data: